pipeline {
	agent {
        node { 
			//label "docker-katalon-ch"
			label "slave-ncias-d2940-c"
            }
        }

    parameters {

    gitParameter(branchFilter: 'origin/(.*)', 
        defaultValue: 'master', 
        name: 'Tag', 
        type: 'PT_BRANCH_TAG',
        quickFilterEnabled: false, 
        selectedValue: 'DEFAULT', 
        sortMode: 'ASCENDING_SMART', 
        tagFilter: '*', 
        useRepository: 'https://github.com/CBIIT/Commons_Automation')

    string(defaultValue: "Commons_Automation.prj", 
        description: 'Enter the Katalon Project file (include the path relative to the repo root):', 
        name: 'KatalonPrj')

    string(defaultValue: "Test Suites/Canine_TestSuite", 
        description: 'Enter the Katalon Suite Path (not including the test suite file):', 
        name: 'KatalonSuite')

	extendedChoice( 
        name: 'Profile', 
        defaultValue: 'QA_ICDC', 
        description: 'Choose the profile to use', 
        type: 'PT_SINGLE_SELECT',
        value: 'DEV_ICDC,QA_ICDC,STAGE_ICDC,PROD_ICDC,QA_CTDC,QA_MTP,STAGE_MTP,PROD_MTP,QA_INS,QA_CCDC,QA_CDS,QA_CCDI_HUB,QA_CRDC_DH,STAGE_CRDC_DH,QA_CCDI' )

	string(defaultValue: "gayathri.radhakrishnan@nih.gov,laxmi.lolla@nih.gov,sohil.sohil@nih.gov", 
        description: 'Enter a list of email addresses to notify in case of test failures:', 
        name: 'EmailRecipients')

        }

    stages{
        stage('checkout'){
            steps {

                checkout([$class: 'GitSCM', 
                    branches: [[name: "${params.Tag}"]], 
                    doGenerateSubmoduleConfigurations: false,
					extensions: [],
					submoduleCfg: [], 
                    userRemoteConfigs: [[url: 'https://github.com/CBIIT/Commons_Automation']]])

                }
            }
		stage('set Profile'){
		    environment {
                KATALON_PRJ         =   "${params.KatalonPrj}"
                }
			steps {
                
				script {
					currentBuild.displayName = "#${env.BUILD_NUMBER} (${params.KatalonSuite} - ${params.Profile})"
					}
				
				script {
				    switch("${params.Profile}") {
                    case ~/[\w\/]+ICDC$/:
						PROJECT="ICDC"
						withCredentials([string(credentialsId: 'Sharepoint_Email', variable: 'results_email'),
						  string(credentialsId: 'Sharepoint_Url_ICDC', variable: 'sharepoint_url')]) {
                            RESULTS_URL="${sharepoint_url}"
							RESULTS_EMAIL="${results_email}"
                            }
                        break

					case ~/[\w\/]+MTP$/:
						PROJECT="MTP"
						withCredentials([string(credentialsId: 'Sharepoint_Email', variable: 'results_email'),
						  string(credentialsId: 'Sharepoint_Url_MTP', variable: 'sharepoint_url')]) {
                            RESULTS_URL="${sharepoint_url}"
							RESULTS_EMAIL="${results_email}"
                            }
                        break

					case ~/[\w\/]+INS$/:
						PROJECT="INS"
						withCredentials([string(credentialsId: 'Sharepoint_Email', variable: 'results_email'),
						  string(credentialsId: 'Sharepoint_Url_INS', variable: 'sharepoint_url')]) {
                            RESULTS_URL="${sharepoint_url}"
							RESULTS_EMAIL="${results_email}"
                            }
                        break

					case ~/[\w\/]+CCDC$/:
						PROJECT="CCDC"
						withCredentials([string(credentialsId: 'Sharepoint_Email', variable: 'results_email'),
						  string(credentialsId: 'Sharepoint_Url_CCDC', variable: 'sharepoint_url')]) {
                            RESULTS_URL="${sharepoint_url}"
							RESULTS_EMAIL="${results_email}"
                            }
                        break

					case ~/[\w\/]+CDS$/:
						PROJECT="CDS"
						withCredentials([string(credentialsId: 'Sharepoint_Email', variable: 'results_email'),
						  string(credentialsId: 'Sharepoint_Url_CDS', variable: 'sharepoint_url')]) {
                            RESULTS_URL="${sharepoint_url}"
							RESULTS_EMAIL="${results_email}"
                            }
                        break

					case ~/[\w\/]+CCDI_HUB$/:
						PROJECT="CCDI_HUB"
						withCredentials([string(credentialsId: 'Sharepoint_Email', variable: 'results_email'),
						  string(credentialsId: 'Sharepoint_Url_CCDI_HUB', variable: 'sharepoint_url')]) {
                            RESULTS_URL="${sharepoint_url}"
							RESULTS_EMAIL="${results_email}"
                            }
                        break

					case ~/[\w\/]+CRDC-DH$/:
						PROJECT="CRDC-DH"
						withCredentials([string(credentialsId: 'Sharepoint_Email', variable: 'results_email'),
						  string(credentialsId: 'Sharepoint_Url_CRDC_DH', variable: 'sharepoint_url')]) {
                            RESULTS_URL="${sharepoint_url}"
							RESULTS_EMAIL="${results_email}"
                            }
                        break

					case ~/[\w\/]+CCDI$/:
						PROJECT="CCDI"
						withCredentials([string(credentialsId: 'Sharepoint_Email', variable: 'results_email'),
						  string(credentialsId: 'Sharepoint_Url_CCDI', variable: 'sharepoint_url')]) {
                            RESULTS_URL="${sharepoint_url}"
							RESULTS_EMAIL="${results_email}"
                            }
                        break
					}

					switch("${params.Profile}") {

					// ICDC
					case "DEV_ICDC":
						TIER="DEV"
						withCredentials([file(credentialsId: 'Katalon_Dev_ICDC', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break
                    case "QA_ICDC":
						TIER="QA"
						withCredentials([file(credentialsId: 'Katalon_QA_ICDC', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break
                    case "STAGE_ICDC":
						TIER="STAGE"
						withCredentials([file(credentialsId: 'Katalon_STAGE_ICDC', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break
                    case "PROD_ICDC":
						TIER="PROD"
						withCredentials([file(credentialsId: 'Katalon_PROD_ICDC', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break

                    // MTP
					case "QA_MTP":
						TIER="QA"
						withCredentials([file(credentialsId: 'Katalon_QA_MTP', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break
					case "STAGE_MTP":
						TIER="STAGE"
						withCredentials([file(credentialsId: 'Katalon_STAGE_MTP', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break
					case "PROD_MTP":
						TIER="PROD"
						withCredentials([file(credentialsId: 'Katalon_PROD_MTP', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break

                    // INS
					case "QA_INS":
						TIER="QA"
						withCredentials([file(credentialsId: 'Katalon_QA_INS', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break

                    // CCDC
					case "QA_CCDC":
						TIER="QA"
						withCredentials([file(credentialsId: 'Katalon_QA_CCDC', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break

					// CDS
					case "QA_CDS":
						TIER="QA"
						withCredentials([file(credentialsId: 'Katalon_QA_CDS', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break

					// CCDI_HUB
					case "QA_CCDI_HUB":
						TIER="QA"
						withCredentials([file(credentialsId: 'Katalon_QA_CCDI_HUB', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break

					// CRDC Hub
					case "QA_CRDC_DH":
						TIER="QA"
						withCredentials([file(credentialsId: 'Katalon_QA_CRDC_DH', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break

					case "STAGE_CRDC_DH":
						TIER="STAGE"
						withCredentials([file(credentialsId: 'Katalon_STAGE_CRDC_DH', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break

					// CCDI
					case "QA_CCDI":
						TIER="QA"
						withCredentials([file(credentialsId: 'Katalon_QA_CCDI', variable: 'pass_file')]) {
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break

					// CTDC
					case "QA_CTDC":
						WIKI_PAGE="289178298"
						PROJECT="CTDC"
						TIER="QA"
						withCredentials([string(credentialsId: 'Box_Email_QA_CTDC', variable: 'box_email'),
						  string(credentialsId: 'Box_Url_QA_CTDC', variable: 'box_url'),
						  file(credentialsId: 'Katalon_QA_CTDC', variable: 'pass_file')]) {
                            RESULTS_URL="${box_url}"
							RESULTS_EMAIL="${box_email}"
							PROFILE="${pass_file}"
							sh "cp ${pass_file} ${WORKSPACE}/Profiles/"
                            }
                        break
                       }
                    }
				}
			}

		stage('run tests'){
            environment {
				KATALON_BROWSER     =   "Chrome"
				KATALON_PROFILE     =   "${params.Profile}"
                KATALON_PRJ         =   "${params.KatalonPrj}"
                KATALON_SUITE_PATH  =   "${params.KatalonSuite}"
				PROFILE_FILE        =   "${PROFILE}"
            }

			agent {
                docker {
                    image 'katalonstudio/katalon:8.5.5'
                    //args '--net=host -u root -v /var/run/docker.sock:/var/run/docker.sock'
                    args '--net=host -u root'
                    reuseNode true
                }
            }

            steps {

				script {
						withCredentials([string(credentialsId: 'Katalon_API_Key', variable: 'api_key'),
						    string(credentialsId: 'Katalon_Org_ID', variable: 'org_id')]) {

							sh label: 'Katalon-Tests', script: '''#!/bin/bash
								
								# Set datestamp for results file
								dateStamp=$(date +%Y%m%d)
								reportFile="${KATALON_PROFILE}_${dateStamp}_build_${BUILD_NUMBER}"

								# Recreate the results directory
								rm -rf results && mkdir results
								
								# Create the output files directory (required for writing excel files)
								rm -rf OutputFiles && mkdir OutputFiles
								
								# Update profile filename
								profile_file=$(basename $PROFILE_FILE)
								profile_name="${profile_file%.*}"
								
								#################### UPDATE CHROME DRIVER (v108 - for Katalonstudio 5.5) ####################
								
								# add unzip package
								apt-get update && apt-get install -y unzip zip

								# Echo versions
								echo "Pre Update:"
								google-chrome --version
								/opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64/chromedriver --version
								
								# get chromedriver v108.x
								wget https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_linux64.zip
								
								# backup and replace chromedriver
								mv /opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64/chromedriver /opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64/chromedriver.bak
								unzip chromedriver_linux64.zip
								mv chromedriver /opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64/
								
								# Echo versions
								echo "Post Update:"
								google-chrome --version
								/opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64/chromedriver --version
								
								#############################################################################################

								#echo "projectPath=$WORKSPACE/$KATALON_PRJ testSuitePath=$KATALON_SUITE_PATH executionProfile=$profile_name filename=$profile_file"
								
								# Run Katalon Tests
								katalonc -noSplash -runMode=console --config -projectPath="$WORKSPACE/$KATALON_PRJ" -retry=0 -testSuitePath="$KATALON_SUITE_PATH" -executionProfile="$profile_name" -browserType="$KATALON_BROWSER (headless)" -reportFolder="results" -reportFileName="$reportFile" -apiKey="$api_key" -orgID="$org_id"

								'''

							}
						}

                }
            }
        }
		post {
			always {

				publishHTML([allowMissing: true,
					alwaysLinkToLastBuild: false,
					keepAll: false,
					reportDir: 'results',
					reportFiles: '*.html',
					reportName: 'HTML Report',
					reportTitles: ''])

				script {

					sh label: 'Zip-Katalon-Results', script: '''#!/bin/bash

					#mv /etc/apt/sources.list.d/google-chrome.list /etc/apt/sources.list.d/google-chrome.list.bak && apt-get update && apt-get install -y zip
					
					resultsFile=$(basename results/*.html)
					zipFile=$(basename -s .html results/*.html)
					
					zip -r results/$zipFile.zip OutputFiles
					#zip -u results/$zipFile.zip results/$resultsFile
					zip -u -r results/$zipFile.zip Reports
					zip -u -r results/$zipFile.zip results

					'''

				}
				
				emailext(attachmentsPattern: 'results/*.zip',
					body: "Katalon Test Results - ${PROJECT}.${TIER}.${BUILD_NUMBER}",
                    subject: "Katalon Test Results - ${PROJECT}.${TIER}.${BUILD_NUMBER}",
                    to: "${RESULTS_EMAIL}")

				script {
				
				    ERROR_OUTPUT = sh (label: 'Katalon-Results-Parsing', script: '''#!/bin/bash
				
					project=''' + PROJECT + '''
					tier=''' + TIER + '''
					inputFile=$(exec find $WORKSPACE/results -type f -name "*.xml")

					# Get test stats
					totalTestCases="$(grep -c '<testcase' $inputFile)"
					passedTestCases="$(grep '<testcase' $inputFile | grep -c 'PASSED')"
					failedTestCases="$(grep '<testcase' $inputFile | grep -c 'FAILED')"
					errorTestCases="$(grep '<testcase' $inputFile | grep -c 'ERROR')"
				
					# function to read output file: JUnit.xml
					parse_results_xml(){
						error_message="Katalon Test results for the latest run on $project $tier (browser tested: $Browser): \\n\\n Total Tests Cases:     $totalTestCases \\n Passed Test Cases:     $passedTestCases \\n Failed Test Cases:     $failedTestCases \\n Errored Test Cases:    $errorTestCases \\n\\n"

						IFS=$'\\n'
						for line in $(grep '<testcase' $inputFile)
						do
						  if [[ "$line" =~ .*"FAILED" || "$line" =~ .*"ERROR" ]]
					      then
							  error_message+="$(echo $line | cut -d '=' -f 2 | cut -d '"' -f 2) \\n "
						  fi
						done
						}
				
						# Get test failures
						parse_results_xml
												
						error_message="\'$error_message\'"
						echo $error_message
				
                      ''',
						returnStdout: true).trim()
				
                    }

				script {
					EMAIL_BODY = sh (label: 'Get-Email-Body', script: '''#!/bin/bash

					emailBody=''' + ERROR_OUTPUT + '''
					resultsUrl=''' + RESULTS_URL + '''
					resultsFile=$(basename results/*.zip)
					emailBody="<b> $emailBody"
					emailBody=${emailBody/\\\\n\\\\n/</b><br><br>}
					emailBody=${emailBody//\\\\n/<br>}
					emailBody="$emailBody <br><br><br> The results of this test run can be found at:  <a href=\\\"$resultsUrl\\\">$resultsFile</a>"
					echo $emailBody

					''',
					returnStdout: true).trim()

					}

				emailext(attachmentsPattern: 'results/*.zip',
					mimeType: 'text/html',
					body: "${EMAIL_BODY}",
					subject: 'Katalon Tests: results attached',
					to: "${EmailRecipients}")
					
				
				}
			
			failure {

				script {
				
				    ERROR_OUTPUT = sh (label: 'Katalon-Results-Parsing', script: '''#!/bin/bash
				
					project=''' + PROJECT + '''
					tier=''' + TIER + '''
					inputFile=$(exec find $WORKSPACE/results -type f -name "*.xml")

					# Get test stats
					totalTestCases="$(grep -c '<testcase' $inputFile)"
					passedTestCases="$(grep '<testcase' $inputFile | grep -c 'PASSED')"
					failedTestCases="$(grep '<testcase' $inputFile | grep -c 'FAILED')"
					errorTestCases="$(grep '<testcase' $inputFile | grep -c 'ERROR')"
				
					# function to read output file: JUnit.xml
					parse_results_xml(){
						error_message="Katalon Test results for the latest run on $project $tier (browser tested: $Browser): \\n\\n Total Tests Cases:     $totalTestCases \\n Passed Test Cases:     $passedTestCases \\n Failed Test Cases:     $failedTestCases \\n Errored Test Cases:    $errorTestCases \\n\\n"

						IFS=$'\\n'
						for line in $(grep '<testcase' $inputFile)
						do
						  if [[ "$line" =~ .*"FAILED" || "$line" =~ .*"ERROR" ]]
					      then
							  error_message+="$(echo $line | cut -d '=' -f 2 | cut -d '"' -f 2) \\n "
						  fi
						done
						}
				
						# Get test failures
						parse_results_xml
												
						error_message="\'$error_message\'"
						echo $error_message
				
                      ''',
						returnStdout: true).trim()
				
                    }
				
				script {

					withCredentials([string(credentialsId: 'Katalon_Slack_URL', variable: 'slack_url')]) {
						
						sh label: 'Katalon-Results-Slack', script: '''#!/bin/bash

						slackHeaders="\'Content-type: application/json\'"

						# POST function to send to Slack
						post_message_to_slack(){
								curlCMD="curl --silent --max-time 10 --request POST --header $slackHeaders --data $payload $slack_url"
								slackError=$(eval $curlCMD)
								echo "Slack Error:   $slackError"
								}

						errorOutput=''' + ERROR_OUTPUT + '''
						resultsUrl=''' + RESULTS_URL + '''
						resultsFile=$(basename results/*.zip)
						errorOutput="$errorOutput \\n\\n @<!channel> The results of this test run can be found at:  <$resultsUrl|$resultsFile>"
						payload="\'{\\\"text\\\":\\\"$errorOutput\\\"}\'"
						post_message_to_slack
							'''
						
						}
					
					}
					
					
				}
				
			cleanup {
	
	            cleanWs()
    
	            }

			}
	}