---
# vars file for cicd
env_file_home: /local/content/docker
# redis config
enable_redis: 'true'
#enable_redis_filter: "{{ lookup('env','ENABLE_REDIS_FILTER') }}"
use_cluster: 'false'
redis_host: 
  dev: "10.208.2.75"
  qa: "10.208.10.169"
  stage: "10.208.18.154"
  prod: "10.208.26.156"
  demo: "10.208.6.182"
redis_password: ""
redis_port: 6379
home: /local/content/docker
tier: "{{ lookup('env','TIER') }}"
prod: prod
platform: "cloudone"
backend_git_tag: "{{ lookup('env','BACKEND_GIT_TAG') }}"
frontend_git_tag: "{{ lookup('env','FRONTEND_GIT_TAG') }}"
frontend_version: "{{ lookup('env','FE_VERSION') }}"
docker_host: "{{ lookup('env','DOCKER_HOST') }}"
tls_hostname: "{{ lookup('env','TLS_HOSTNAME') }}"
fence_id: "{{ lookup('env','FENCE_ID') }}"
backend_version: "{{ lookup('env','BE_VERSION') }}"
workspace: "{{ lookup('env','WORKSPACE') }}"
docker_user: "{{ lookup('env','DOCKER_USER') }}"
docker_password: "{{ lookup('env','DOCKER_PASSWORD') }}"
build_number: "{{ lookup('env','BUILD_NUMBER')}}"

neo4j_ip: "{{ lookup('env','NEO4J_IP') }}"
neo4j_bearer: "{{ lookup('env','BEARER') }}"
neo4j_user: "{{ lookup('env','NEO4J_USER') }}"
neo4j_password: "{{ lookup('env','NEO4J_PASS') }}"

region: us-east-1
newrelic_license_key: "{{ lookup('env','NEWRELIC_LIC_KEY')}}"
sumo_access_id: "{{ lookup('env','SUMO_ACCESS_ID')}}"
sumo_access_key: "{{ lookup('env','SUMO_ACCESS_KEY')}}"
# syslog_host: "{{ lookup('env','SYSLOG_HOST')}}"
syslog_host: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
app_name: icdc-{{ platform }}-{{ tier }}
schema_file: icdc.graphql
backend_user_info: https://caninecommons.cancer.gov/fence/login/
backend_fence_login: https://nci-crdc-staging.datacommons.io/user/oauth2/authorize?client_id={{ fence_id }}&response_type=code&redirect_uri=https%3A%2F%2Fcaninecommons.cancer.gov%2F&scope=openid%20user
backend_fence_logout: https://caninecommons.cancer.gov/fence/logout
#backend_content_url: "{% if tier == prod %}https://raw.githubusercontent.com/CBIIT/bento-icdc-frontend/master/src/content/prod/aboutPagesContent.yaml{% else %}https://raw.githubusercontent.com/CBIIT/bento-icdc-frontend/Develop/src/content/pre-prod/aboutPagesContent.yaml{% endif %}"
bento_api_version: "{{ backend_version }}"
backend_frontend_version: "{{frontend_version }}"
backend_google_analytics_id: UA-154442677-1
dev_alb_dns_name: internal-dev-a-appli-caninedata-8uhlkjyn-1830173970.us-east-1.elb.amazonaws.com
frontend_url: "{% if tier == 'prod' %}https://caninecommons.cancer.gov/{% else %}https://caninecommons-{{ tier }}.cancer.gov/{% endif %}" 

## ES ##
es_schema_file: "es-schema-icdc.graphql"
es_host: "{{ lookup('env','ES_HOST') }}"

## Static Content ##
react_app_landing_data:
  dev: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/develop/landingView.yaml"
  qa: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/qa/landingView.yaml"
  stage: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/stage/landingView.yaml"
  prod: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/production/landingView.yaml"

react_app_news_data:
  dev: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/develop/newsView.yaml"
  qa: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/qa/newsView.yaml"
  stage: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/stage/newsView.yaml"
  prod: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/production/newsView.yaml"

react_app_about_data:
  dev: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/develop/aboutPagesContent.yaml"
  qa: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/qa/aboutPagesContent.yaml"
  stage: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/stage/aboutPagesContent.yaml"
  prod: "https://raw.githubusercontent.com/CBIIT/bento-icdc-static-content/production/aboutPagesContent.yaml"

## data-dictionary ##
react_app_model_url:
  dev: "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/develop/model-desc/icdc-model.yml"
  qa: "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/develop/model-desc/icdc-model.yml"
  stage: "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/master/model-desc/icdc-model.yml"
  prod: "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/master/model-desc/icdc-model.yml"

react_app_model_props_url:
  dev: "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/develop/model-desc/icdc-model-props.yml"
  qa: "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/develop/model-desc/icdc-model-props.yml"
  stage: "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/master/model-desc/icdc-model-props.yml"
  prod: "https://raw.githubusercontent.com/CBIIT/icdc-model-tool/master/model-desc/icdc-model-props.yml"

react_app_readme_url:
  dev: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/dev/Data_Model_Navigator_README.md"
  qa: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/qa/Data_Model_Navigator_README.md"
  stage: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/stage/Data_Model_Navigator_README.md"
  prod: "https://raw.githubusercontent.com/CBIIT/icdc-readMe-content/prod/Data_Model_Navigator_README.md"
#cloudfront_domain_name: "{% if tier == 'prod' or tier == 'stage' %}{{ lookup('amazon.aws.aws_secret', 'cloudfront.domain_name', nested=true, region='us-east-1' ) }}{% else %}''{% endif %}"
#cloudfront_key_group_id: "{% if tier == 'prod' or tier == 'stage' %}{{ lookup('amazon.aws.aws_secret', 'cloudfront.key_group_id', nested=true, region='us-east-1' ) }}{% else %}''{% endif %}"
#cloudfront_private_key: "{% if tier == 'prod' or tier == 'stage' %}{{ lookup('amazon.aws.aws_secret', 'cloudfront.privatekey', nested=true, region='us-east-1' ) }}{% else %}''{% endif %}"
files_version: "{{ lookup('env','FILES_VERSION') }}"
project_name: icdc
url_src: "{% if tier == 'prod' or tier == 'stage' %}CLOUD_FRONT{% else %}indexd{% endif %}"
indexd_url: "{{ lookup('aws_secret', 'bento/{{ project_name }}/{{ tier }}.indexd_url', nested=true, region='us-east-1') }}"
auth_enabled: "false"
interoperation_version: "{{ lookup('env','INTEROPERATION_VERSION') }}"
s3_access_key_id: "{{ lookup('env','s3_access_key_id') }}"
3_secret_access_key: "{{ lookup('env','s3_secret_access_key') }}"
file_manifest_bucket_name: "{{ lookup('env','file_manifest_bucket_name') }}"
cloudfront_key_pair_id: "{{ lookup('env','cloudfront_key_pair_id') }}"
cloudfront_private_key: "{{ lookup('env','cloudfront_private_key') }}"
cloudfront_domain: "{{ lookup('env','cloudfront_domain',') }}"
cloudfront_key_group_id: "{{ lookup('env','cloudfront.key_group_id',') }}"
cloudfront_domain_name: "{{ lookup('env','cloudfront.domain_name',') }}"
#s3_access_key_id: "{{ lookup('aws_secret', 'bento/icdc/stage.s3_access_key_id', nested=true, region='us-east-1') }}"
#s3_secret_access_key: "{{ lookup('aws_secret', 'bento/icdc/stage.s3_secret_access_key', nested=true, region='us-east-1') }}"
#file_manifest_bucket_name: "{{ lookup('aws_secret', 'bento/icdc/stage.file_manifest_bucket_name', nested=true, region='us-east-1') }}"
#cloudfront_key_pair_id: "{{ lookup('aws_secret', 'bento/icdc/stage.cloudfront_key_pair_id', nested=true, region='us-east-1') }}"
#cloudfront_IO_private_key: "{{ lookup('aws_secret', 'bento/icdc/stage.cloudfront_private_key', nested=true, region='us-east-1') | b64decode }}"
#cloudfront_domain: "{{ lookup('aws_secret', 'bento/icdc/stage.cloudfront_domain', nested=true, region='us-east-1') }}"