---
- name: Get the current caller identity information
  aws_caller_info:
  register: caller_info

- name: set ECR registry name
  set_fact:
    ecr_repo: "{{ caller_info.account }}.dkr.ecr.{{ region }}.amazonaws.com"

- name: login into ecr
  shell: "docker login -u AWS -p $(aws ecr get-login-password --region {{ region }}) {{ecr_repo}}"
  ignore_errors: True
  register: ecr_login

- name: backend image
  block:
    - name: get backend image vulnerabilities
      command: "trivy image {{ ecr_repo }}/{{ project }}-backend:release"
      register: backend_vuln
  always:
    - name: echo backend vulnerabilities
      debug:
        msg: "{{ backend_vuln.stdout_lines }}"

- name: test backend image
  command: "trivy image --exit-code 1 --severity HIGH,CRITICAL {{ ecr_repo }}/{{ project }}-backend:release"