apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bento-dev-backend-version
  description: Retrieve backend version
spec:
  type: openapi
  lifecycle: development
  owner: bento-dev-team
  system: bento-dev
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Version API
      license:
        name: MIT
    servers:
      - url: https://bento-dev.bento-tools.org
    paths:
      /version:
        get:
          summary: List API version