apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bento-dev-backend
  description: backend service
spec:
  type: service
  lifecycle: development
  owner: bento-dev-team
  system: bento-dev

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bento-dev-backend-version
  description: Retrieve backend version
spec:
  type: openapi
  lifecycle: development
  owner: bento-dev-team
  system: bento-dev
  definition: |
    servers:
      - url: https://bento-dev.bento-tools.org
    paths:
      /version:
        get:
          summary: List API version