apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bento-dev-backend
  description: backend service
spec:
  type: service
  lifecycle: development
  owner: bento-dev-team
  system: bento-dev
  providesApis:
    - bento-dev-backend-version