pipeline {
	agent {
		node {
			label 'commons-docker-ncias-p2236-v'
		}
	}
	parameters {
    string(
        name: 'Hostname',
        defaultValue: 'create', 
        description: 'Enter the hostname of the agent',
        )
  }
  options {
  	ansiColor('xterm')
  }
  tools {
  	maven 'Default' 
    jdk 'Default' 
  }
  stages{
  	stage('checkout'){
  		steps {

  			checkout( poll: false, 
				changelog:false,
				scm: [$class: 'GitSCM', 
				branches: [[name: '*/master']], 
				doGenerateSubmoduleConfigurations: false, 
				extensions: [[$class: 'DisableRemotePoll'],
				[$class: 'PathRestriction', excludedRegions: '*'], 
				[$class: 'RelativeTargetDirectory', 
				relativeTargetDir: 'icdc-devops']], 
				submoduleCfg: [], 
				userRemoteConfigs: 
				[[url: 'https://github.com/CBIIT/icdc-devops.git']]])
        
        }
 
  	}
  	stage('build'){
 		steps {
 			wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
                  sh """echo  "[agent]\n${params.Hostname}" > ${WORKSPACE}/icdc-devops/ansible/host"""
                  sh "cat ${WORKSPACE}/icdc-devops/ansible/host"
                  ansiblePlaybook(
                        playbook: "${WORKSPACE}/icdc-devops/ansible/initialize-jenkins-agent.yml",
                        inventory: "${WORKSPACE}/icdc-devops/ansible/hosts",
                        credentialsId: "commonsdocker",
                        extraVars: [host: "${params.Hostname}"],
                        become: true,
                        hostKeyChecking: false,
                        colorized: true)
 		    }
 		}
 	}
  }
  post {
    always {
      sh "echo end of pipeline"
      // cleanWs()
    }
  }
}