---
- name: setup sumologic and newrelic agents
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars_files:
    - vars.yml

  roles:
    - sumologic
    - sumologic-journalctl
    - newrelic