- name: build auth microservice
  hosts: all
  connection: local
  gather_facts: no
  become: yes

  vars:
    workspace: "{{ lookup('env','WORKSPACE') }}"

  tasks:
    #install collections
    - name: install aws collection
      command: ansible-galaxy collection install {{item}}
      loop:
        - community.docker
        - amazon.aws
        - community.aws:<=3.2.0
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main
    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1
    - name: checkout any submodules
      command: git submodule update --init --recursive
      args:
        chdir: "{{workspace}}/{{checkout_directory}}"
      register: output
      when:
        - project_name: "bento"
    - debug:
        msg: "{{output.stdout_lines}}"
    #build backend
    - name: build {{project_name}} auth microservice
      include_role:
        name: bento.common.build_auth
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER')}}"
        project_name: "{{ project_name }}"
        project: "{{ project_name }}"
        image_version: "{{ lookup('env','AUTH_VERSION') }}"
        tier: "{{ tier }}"
        container_name: "auth"
        dockerfile_path: "{{workspace}}/playbooks/docker/dockerfiles/auth-microservice-dockerfile"
        container_image: "{{ ecr_repo }}/{{ project_name }}-{{ container_name }}:{{ image_version }}"
        container_registry_url: "{{ ecr_repo }}"
        container_build_path: "{{workspace}}/bento-auth"
