- name: files microservice pipeline
  hosts: bento
  connection: local
  gather_facts: no
  become: yes

  tasks:
    - name: install aws collection
      command: ansible-galaxy collection install --force {{item}}
      loop:
        - community.docker
        - amazon.aws
        - community.aws:<=3.2.0
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main

    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1

    #build files
    - name: build stage for neo4j microservice
      include_role:
        name: bento.common.neo4j
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER')}}"
        project_name: "{{ project_name }}"
        image_version: "{{ lookup('env','NEO4J_VERSION') }}"
        container_name: "neo4j"
        container_build_path: "{{ workspace }}/{{ project_name }}-neo4j"
        dockerfile_path: "{{ workspace }}/playbooks/docker/dockerfiles/neo4j-microservice-dockerfile"
        container_registry_url: "{{ ecr_repo }}"