- name: build auth microservice
  hosts: all
  connection: local
  gather_facts: no
  become: yes

  tasks:
    #install collections
    - name: install aws collection
      command: ansible-galaxy collection install {{item}}
      loop:
        - community.docker
        - amazon.aws
        - community.aws:<=3.2.0
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main
    #docker login
    - name: docker login
      include_role:
        name: bento.common.ecr_login
      vars:
        region: us-east-1
    - debug:
        msg: "Here is the ECR repo {{ecr_repo}}"
    #build backend
    - name: build {{project_name}} auth microservice
      include_role:
        name: bento.common.build_auth
      vars:
        ansible_python_interpreter: /usr/bin/python3
#        auth_version: "{{ lookup('env','AUTH_VERSION') }}"
#        auth_container_name: "auth"
#        auth_image_version: "{{ auth_version }}"
#        auth_container_build_path: "{{workspace}}/bento-auth"
#        auth_dockerfile_path: "{{workspace}}/icdc-devops/docker/dockerfiles/auth-microservice-dockerfile"
#        auth_container_image: "{{ecr_repo}}/{{project_name}}-{{container_name}}:{{auth_version}}-{{build_number}}"
#        auth_container_port: "8082"
#        auth_container_memory: "512"
#        auth_container_cpu: "256"
#        auth_ecs_cluster_name: "{{project_name}}-{{tier}}-ecs"
#        auth_container_image_url: "{{ecr_repo}}/{{project_name}}-{{container_name}}"
        workspace: "{{ lookup('env','WORKSPACE') }}"
        build_number: "{{ lookup('env','BUILD_NUMBER')}}"
        project_name: "{{ project_name }}"
        project: "{{ project_name }}"
        image_version: "{{ lookup('env','AUTH_VERSION') }}"
        tier: "{{ tier }}"
        container_name: "auth"
        dockerfile_path: "{{workspace}}/icdc-devops/docker/dockerfiles/auth-microservice-dockerfile"
        container_image: "{{ ecr_repo }}/{{ project_name }}-{{ container_name }}:{{ image_version }}"
        container_registry_url: "{{ ecr_repo }}"
        container_build_path: "{{ auth_container_build_path }}"
