- name: deploy neo4j microservice db
  hosts: all
  connection: local
  gather_facts: yes
  become: yes

  vars:
    - ecs_cluster_name: "{{ project_name }}-{{ tier }}-ecs"
    - ecs_service_name: "{{service_name}}"

  tasks:
    #install collections
    - name: install aws collection
      command: ansible-galaxy collection install {{item}}
      loop:
        - community.docker
        - amazon.aws
        - community.aws:<=3.2.0
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main

    - name: shutdown ecs service
      community.aws.application_autoscaling_policy:
        state: present
        policy_name: "{{project_name}}-{{ecs_service_name}}-shutdown-policy"
        service_namespace: ecs
        resource_id: "service/{{ecs_cluster_name}}/{{ecs_service_name}}"
        scalable_dimension: ecs:service:DesiredCount
        policy_type: TargetTrackingScaling
        minimum_tasks: 0
        maximum_tasks: 0
        target_tracking_scaling_policy_configuration:
          TargetValue: 60
          PredefinedMetricSpecification:
            PredefinedMetricType: ECSServiceAverageCPUUtilization
          ScaleOutCooldown: 60
          ScaleInCooldown: 60