- name: etl
  hosts: all
  connection: local
  gather_facts: no
#  become: yes

  tasks:
    #install collections
    - name: install aws collection
      command: ansible-galaxy collection install {{item}}
      loop:
        - community.docker
        - amazon.aws
        - community.aws:<=3.2.0
        - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,main
    
    #run data loader
    - name: perform etl
      include_role:
        name: bento.common.etl
      vars:
        workspace: "{{ lookup('env','WORKSPACE') }}"
        ansible_python_interpreter: /usr/bin/python3