- name: initialize jenkins
  hosts: agent
  gather_facts: yes
  become: yes
  become_method: "sudo"

  tasks:
    - name: install python3
      yum:
        name:
          - python3
          - python3-devel
          - git
        state: installed